version: '2'
services:
  server:
    image: kyijulie/heroplayer:latest
    ports: 
      - 9001:9001
    depends_on: 
      - db
    restart: always
    environment: 
      - DATABASE_URL=postgres://postgres@db:5432/starkcloud
  db:
    image: postgres
    restart: always